//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountType
    {
        public AccountType()
        {
            this.BankingPackets = new HashSet<BankingPacket>();
        }
    
        public int ID { get; set; }
        public string TypeOfAccount { get; set; }
    
        public virtual ICollection<BankingPacket> BankingPackets { get; set; }
    }
}
