//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login2
{
    using System;
    
    public partial class addHistoryTransaction1_Result1
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> UserAccountID { get; set; }
        public string fromAccount { get; set; }
        public string toWichAccount { get; set; }
        public Nullable<int> TypeTransaction { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<System.DateTime> DateTransaction { get; set; }
    }
}
