//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankingPacket
    {
        public BankingPacket()
        {
            this.ComisionStatus = new HashSet<ComisionStatu>();
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDTypePacket { get; set; }
        public Nullable<int> AccountType { get; set; }
    
        public virtual AccountType AccountType1 { get; set; }
        public virtual TypeBankingPacket TypeBankingPacket { get; set; }
        public virtual ICollection<ComisionStatu> ComisionStatus { get; set; }
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
    }
}
