//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComisionStatu
    {
        public int ID { get; set; }
        public Nullable<int> IDTypeTransaction { get; set; }
        public Nullable<int> IDBankPacket { get; set; }
        public Nullable<double> Comision { get; set; }
    
        public virtual BankingPacket BankingPacket { get; set; }
        public virtual TypesTransaction TypesTransaction { get; set; }
    }
}
