//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Companies = new HashSet<Company>();
            this.HistoryTransactions = new HashSet<HistoryTransaction>();
            this.IndividualCustomers = new HashSet<IndividualCustomer>();
            this.NormalUsers = new HashSet<NormalUser>();
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int ID { get; set; }
        public int CustomerType { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
        public virtual CustomerType CustomerType1 { get; set; }
        public virtual ICollection<HistoryTransaction> HistoryTransactions { get; set; }
        public virtual ICollection<IndividualCustomer> IndividualCustomers { get; set; }
        public virtual ICollection<NormalUser> NormalUsers { get; set; }
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
    }
}
