//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.BankAdmins = new HashSet<BankAdmin>();
        }
    
        public int ID { get; set; }
        public int IndividualID { get; set; }
    
        public virtual ICollection<BankAdmin> BankAdmins { get; set; }
        public virtual Individual Individual { get; set; }
    }
}
