//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryTransaction
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> UserAccountID { get; set; }
        public Nullable<int> TypeTransaction { get; set; }
        public Nullable<System.DateTime> DateTransaction { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual TypesTransaction TypesTransaction { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
