//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MitBankDBEntities : DbContext
    {
        public MitBankDBEntities()
            : base("name=MitBankDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CompaniesView> CompaniesViews { get; set; }
        public DbSet<CustomersView> CustomersViews { get; set; }
        public DbSet<HistoryTransactionView> HistoryTransactionViews { get; set; }
        public DbSet<IndividualsView> IndividualsViews { get; set; }
        public DbSet<UserAccountsView> UserAccountsViews { get; set; }
        public DbSet<UsernamesView> UsernamesViews { get; set; }
    }
}
