//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypesTransaction
    {
        public TypesTransaction()
        {
            this.ComisionStatus = new HashSet<ComisionStatu>();
            this.HistoryTransactions = new HashSet<HistoryTransaction>();
        }
    
        public int ID { get; set; }
        public string TypeTransaction { get; set; }
    
        public virtual ICollection<ComisionStatu> ComisionStatus { get; set; }
        public virtual ICollection<HistoryTransaction> HistoryTransactions { get; set; }
    }
}
