//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Username
    {
        public int ID { get; set; }
        public int UserType { get; set; }
        public string Username1 { get; set; }
        public string Pass { get; set; }
    
        public virtual NormalUser NormalUser { get; set; }
    }
}
